### PR TITLE
"Hardware Wallets" update

### PR DESCRIPTION
**Pull request by goldfarbas**
- Add a few sentences to "Basic Functionality" 
- Update "Hardware Wallets" section
- Add "Web and Browser Wallets" section
- Add "Mobile Wallets" section

### CODE REVIEW

**Comment by GBKS** [comment]
This is great. What do you think about moving the overview over the different types of wallets below "Advanced functionality"? Right now, it seems a bit out of place at the bottom of "Basic functionality".

**Comment by goldfarbas** [comment]
I agree that the overview of wallet types is out of place but I'm not sure "Advanced functionality" is the right place for it either. Now that I'm looking at the "What's in here" section, I think "Types of Wallets" could even be its own chapter but that leads me to wonder if this is going to be about Crypto UX in general or just Wallet UX.

I don't think there's anything wrong with sticking to wallet UX; we could add a bit in the intro about how wallets are the way people interface with crypto so getting UX right is critical and add the overview of wallet types there.

If you'd rather stick to Crypto UX instead of focusing on wallets, then I think we should move it to the "Multi-coin & digital asset wallets" section in the "Types of software" chapter.

**Comment by GBKS** [comment]
Good thoughts. I'd like to stick with Crypto UX since I'd like the handbook to be open to grow and change along with the space and the interests of the audience and contributors. If somebody wants to add sections about exchanges, they can do that. How the sections are split up will definitely have to change over time.

The way I thought about this page was that the top explains the basic and advanced features/properties, and then  we list out the wallet types below, which each has a different combination of those features/properties. How about that?

**Comment by goldfarbas** [comment]
That makes sense; I'll see about working something up along those lines

**Comment by goldfarbas** [comment]
Just added a few more commits with "Types of wallets" moved below "Advanced functionality," new sentences in each of the wallet types about the advanced functions available, and a list of paper wallets for readers to check out.

I'm still new to Github so please let me know if there's a better way to manage the pull request than just adding new commits every time. Idk if what I'm doing is getting messy or if that's normal or what.

**Comment by GBKS** [comment]
Thank for the updates. I made some minor tweaks:

- Compressed images for lower file size
- Updated width/height of image tags to match the files
- Replaced "We're talking about..." wording since that seems a bit casual

If you give your OK, then I can merge this pull request and push it live.

Using a pull request like you are doing here is the right approach. It allows us to iterate on a specific section and push it live once we're happy with it. How is this process working out for you?

**Comment by goldfarbas** [comment]
Looks good! This works fine, I just might have a question about Github every once in a while.

Like when you say "give your OK," does that mean closing the pull request (which I just did) or just letting you know it's good for you to merge?

**Comment by GBKS** [comment]
Yes, Github takes some time to get used to. Feel free to ask questions any time.

By giving your OK, I just meant that you're good to push your updates live. I just did that by reopening your pull request, merging it into the master branch, and then closing it. Then I pushed the changes to the live site, which is a manual process I do separately.

I'll also make a small update in the next few days to add you as a contributor. Should I use your Github name and profile link? Or do you have another preference?

**Comment by goldfarbas** [comment]
No, Github name and profile works for me. Thanks!

**Pull request merged**
